pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunAzureCLI
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'jjl-trial-subscription'  # Replace with your Azure subscription name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
	az group create --name myapp-rg --location eastus
  	az acr create --resource-group myapp-rg --name jjlcontainerregistry --sku Basic
	az aks create --resource-group myapp-rg --name myapp --node-count 1 --enable-addons monitoring --generate-ssh-keys
    displayName: 'Run Azure CLI Commands'
